#!/bin/bash


# If current work directory is not owned by root
#   1. Update odc user/group to have same UID,GID as work directory
#   2. Relaunch this script as odc user
[[ $UID -ne 0 ]] || {
    target_uid=$(stat -c '%u' .)
    target_gid=$(stat -c '%g' .)

    [[ $target_uid -eq 0 ]] || {
        groupmod --gid "${target_gid}" odc 2> /dev/null > /dev/null
        usermod --gid "${target_gid}" --uid "${target_uid}" odc > /dev/null 2> /dev/null
        chown -R odc:odc /home/odc/
        exec sudo -u odc -E -H bash "$0" "$@"
    }
}

[[ $UID -ne 0 ]] || echo "WARNING: Running as root"

# point pip cache to /wk volume
export PIP_CACHE_DIR=/wk/.cache/pip

case "${1:-help}" in
    help)
        echo "TODO: help"
        ;;
    python|python3|pip|pip3|pip-compile|pytest)
        source /env/bin/activate
        exec "$@"
        ;;
    *)
        exec "$@"
        ;;
esac
