#!/bin/bash

_launch_db () {
    local pgdata="${1:-/srv/postgresql}"
    local bin=$(find /usr/lib/postgresql/ -type d -name bin)

    sudo -u postgres test -e "${pgdata}/PG_VERSION" || {
        sudo -u postgres "${bin}/initdb" -D "${pgdata}" --auth-host=md5 --encoding=UTF8
    }

    sudo -u postgres "${bin}/pg_ctl" -D "${pgdata}" -l "${pgdata}/pg.log" start
}

sudo -u postgres psql -c '\conninfo' 2> /dev/null > /dev/null || {
    echo "Launching DB"
    _launch_db
}

sudo -u postgres psql -c '\du' | grep -qs $USER || {
    export DATACUBE_DB_URL="postgresql://${USER}@/${USER}"

    echo "Creating user: ${USER}"
    sudo -u postgres createuser --superuser ${USER}

    echo "Initialising Test Database"
    createdb ${USER}
    datacube system init
}

[ -z "${1:-}" ] || {
    exec "$@"
}
