[project]
name = "odc-apps-cloud"
dynamic = ["version"]
description = "CLI utils for working with objects/files in the cloud"
authors = [
    {name = "Open Data Cube", email = "earth.observation@ga.gov.au"},
]
dependencies = [
    "click",
    "odc-cloud[ASYNC]",
    "odc-io",
]
requires-python = ">=3.9"
readme = "README.md"
license = "Apache-2.0"

[project.urls]
Homepage = "https://github.com/opendatacube/odc-tools/"

[project.optional-dependencies]
thredds = [
    "odc-cloud[THREDDS]",
]
azure = [
    "odc-cloud[AZURE]",
]
gcp = [
    "google-cloud-storage",
]

[project.scripts]
azure-to-tar = "odc.apps.cloud.azure_to_tar:cli[AZURE]"
gs-to-tar = "odc.apps.cloud.gs_to_tar:cli[GCP]"
redrive-queue = "odc.apps.cloud.redrive_to_queue:cli"
s3-find = "odc.apps.cloud.s3_find:cli"
s3-inventory-dump = "odc.apps.cloud.s3_inventory:cli"
s3-to-tar = "odc.apps.cloud.s3_to_tar:cli"
thredds-to-tar = "odc.apps.cloud.thredds_to_tar:cli[THREDDS]"

[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = {attr = "odc.apps.cloud.__version__"}

[tool.setuptools.packages.find]
include = ["odc*"]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:datetime.datetime.utcnow*:DeprecationWarning:botocore.*"
]
